#Ambiente QA
#service: apolo-fe-qa
#instance_class: F4

#Ambiente Producción
service: default
instance_class: B4
manual_scaling:
  instances: 1

runtime: nodejs14

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto